on:
  push:
    branches:
      - main
  pull_request:

jobs:
  atlas:
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: example
          MYSQL_ROOT_PASSWORD: pass
        ports:
          - "3306:3306"
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ariga/setup-atlas@v0
      with:
        version: 'v0.26.0'
    - name: Apply schema to test database
      run: |
        atlas schema apply \
          --url "mysql://root:pass@localhost:3306/example" \
          --to "file://db/schema/example.hcl" \
          --auto-approve